export {
  DUCKY_MASCOT_SVG_LIGHT,
  DUCKY_MASCOT_SVG_DARK,
  DUCKY_FAVICON_SVG,
} from "./ducky-mascot";

export {
  CERES_FREQUENCY_FAVICON,
  CERES_UTILIZATION_FAVICON,
  CERES_OASIS_FAVICON,
  CERES_DISCIPLINE_FAVICON,
  CERES_COMPLIANCE_FAVICON,
} from "./favicons";
