/**
 * DOCX Render Worker
 *
 * Generates DOCX files from ContentPayload.
 * Reuses Caelum's design tokens and helper patterns from sowDocxExportV2.ts.
 */

import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, LevelFormat, PageNumber,
} from "docx";
import type { ProjectSpec, ContentPayload } from "@shared/models/pipeline";

// ── Design Tokens (consistent with Caelum v2.1 palette) ──

const C = {
  blue: "2E5090",
  darkText: "1A1A1A",
  bodyText: "333333",
  white: "FFFFFF",
  gray: "666666",
  borderGray: "BFBFBF",
  bandingBlue: "F2F6FA",
};

const FONT = "Arial";

// ── Helpers ──

function heading(text: string, level: 1 | 2 | 3): Paragraph {
  const config = {
    1: { heading: HeadingLevel.HEADING_1, size: 28, color: C.blue, before: 360, after: 200 },
    2: { heading: HeadingLevel.HEADING_2, size: 24, color: C.darkText, before: 240, after: 120 },
    3: { heading: HeadingLevel.HEADING_3 as any, size: 22, color: C.darkText, before: 200, after: 100 },
  }[level];

  return new Paragraph({
    heading: config.heading,
    spacing: { before: config.before, after: config.after },
    children: [new TextRun({ text, font: FONT, size: config.size, bold: true, color: config.color })],
  });
}

function para(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text, font: FONT, size: 22, color: C.bodyText })],
  });
}

function bulletItem(text: string): Paragraph {
  return new Paragraph({
    numbering: { reference: "bullets", level: 0 },
    spacing: { after: 60 },
    children: [new TextRun({ text, font: FONT, size: 20, color: C.bodyText })],
  });
}

/**
 * Convert markdown content into DOCX paragraphs.
 * Handles: headings (##), bold (**), bullets (-/•), and plain text.
 */
function markdownToDocxParagraphs(markdown: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const lines = markdown.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Headings
    if (trimmed.startsWith("### ")) {
      paragraphs.push(heading(trimmed.slice(4), 3));
    } else if (trimmed.startsWith("## ")) {
      paragraphs.push(heading(trimmed.slice(3), 2));
    } else if (trimmed.startsWith("# ")) {
      paragraphs.push(heading(trimmed.slice(2), 1));
    }
    // Bullets
    else if (trimmed.startsWith("- ") || trimmed.startsWith("• ") || trimmed.startsWith("* ")) {
      paragraphs.push(bulletItem(trimmed.slice(2)));
    }
    // Bold text handling in paragraphs
    else {
      const runs: TextRun[] = [];
      const parts = trimmed.split(/(\*\*[^*]+\*\*)/);
      for (const part of parts) {
        if (part.startsWith("**") && part.endsWith("**")) {
          runs.push(new TextRun({ text: part.slice(2, -2), font: FONT, size: 22, bold: true, color: C.bodyText }));
        } else if (part) {
          runs.push(new TextRun({ text: part, font: FONT, size: 22, color: C.bodyText }));
        }
      }
      if (runs.length > 0) {
        paragraphs.push(new Paragraph({ spacing: { after: 120 }, children: runs }));
      }
    }
  }

  return paragraphs;
}

export async function renderDocx(spec: ProjectSpec, content: ContentPayload): Promise<Buffer> {
  const children: Paragraph[] = [];

  // Title
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
    children: [new TextRun({ text: spec.title, font: FONT, size: 36, bold: true, color: C.blue })],
  }));

  // Metadata line
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
    children: [new TextRun({
      text: `Audience: ${spec.audience} | Tone: ${spec.tone} | Generated by Forge`,
      font: FONT, size: 18, color: C.gray, italics: true,
    })],
  }));

  // Sections
  for (const section of content.sections) {
    children.push(heading(section.title, section.headingLevel));
    children.push(...markdownToDocxParagraphs(section.content));
  }

  // Ducky footer note
  children.push(new Paragraph({ spacing: { before: 400 }, children: [] }));
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({
      text: "Powered by Ducky Intelligence.",
      font: FONT, size: 16, italics: true, color: C.gray,
    })],
  }));

  const doc = new Document({
    styles: {
      default: { document: { run: { font: FONT, size: 22, color: C.bodyText } } },
      paragraphStyles: [
        {
          id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
          run: { size: 28, bold: true, font: FONT, color: C.blue },
          paragraph: { spacing: { before: 360, after: 200 }, outlineLevel: 0 },
        },
        {
          id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
          run: { size: 24, bold: true, font: FONT, color: C.darkText },
          paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 1 },
        },
      ],
    },
    numbering: {
      config: [
        {
          reference: "bullets",
          levels: [{
            level: 0,
            format: LevelFormat.BULLET,
            text: "\u2022",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 720, hanging: 360 } } },
          }],
        },
      ],
    },
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      headers: {
        default: new Header({
          children: [new Paragraph({
            alignment: AlignmentType.RIGHT,
            border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: C.blue, space: 2 } },
            children: [new TextRun({ text: spec.title, font: FONT, size: 16, italics: true, color: C.gray })],
          })],
        }),
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            border: { top: { style: BorderStyle.SINGLE, size: 4, color: C.blue, space: 2 } },
            children: [
              new TextRun({ text: "Page ", font: FONT, size: 16, color: C.gray }),
              new TextRun({ children: [PageNumber.CURRENT], font: FONT, size: 16, color: C.gray }),
              new TextRun({ text: " | Powered by Ducky Intelligence", font: FONT, size: 16, color: C.gray }),
            ],
          })],
        }),
      },
      children,
    }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
